# Generated by Django 3.1.7 on 2021-03-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenanceticket',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='maintenanceticket',
            old_name='date',
            new_name='submit_date',
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='finish_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='issuer',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='location',
            field=models.CharField(default='Factory_1', max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='start_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
